// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpEMM50oilLx7T75Gc_ATpv3T-R9a3slQ',
    appId: '1:93696971345:web:dfc08b8810e63260dcde70',
    messagingSenderId: '93696971345',
    projectId: 'flutterbookapp-b4e44',
    authDomain: 'flutterbookapp-b4e44.firebaseapp.com',
    storageBucket: 'flutterbookapp-b4e44.appspot.com',
    measurementId: 'G-XWNET0MJB8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuoig3_U293WhE0qmxEEM6HRIMPNjHBX0',
    appId: '1:93696971345:android:06c1b05e0a7b35d9dcde70',
    messagingSenderId: '93696971345',
    projectId: 'flutterbookapp-b4e44',
    storageBucket: 'flutterbookapp-b4e44.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoKuDUXNCbMYLcLG05nm3XRLEUcDdPLvY',
    appId: '1:93696971345:ios:3f901cce330d1200dcde70',
    messagingSenderId: '93696971345',
    projectId: 'flutterbookapp-b4e44',
    storageBucket: 'flutterbookapp-b4e44.appspot.com',
    iosBundleId: 'com.example.libmanagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoKuDUXNCbMYLcLG05nm3XRLEUcDdPLvY',
    appId: '1:93696971345:ios:3f901cce330d1200dcde70',
    messagingSenderId: '93696971345',
    projectId: 'flutterbookapp-b4e44',
    storageBucket: 'flutterbookapp-b4e44.appspot.com',
    iosBundleId: 'com.example.libmanagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpEMM50oilLx7T75Gc_ATpv3T-R9a3slQ',
    appId: '1:93696971345:web:df6a0ec8317ed631dcde70',
    messagingSenderId: '93696971345',
    projectId: 'flutterbookapp-b4e44',
    authDomain: 'flutterbookapp-b4e44.firebaseapp.com',
    storageBucket: 'flutterbookapp-b4e44.appspot.com',
    measurementId: 'G-XDH9YHDP9J',
  );
}
